name: diffdock
channels:
  - pyg
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.18
  - pip
  - python-devtools
  # Need older setuptools for openfold
  - setuptools=69.5.1
  # ProDy needs to be installed with conda
  - prody=2.2.0
  - scipy=1.12.0
  # Need to install torch in order to build openfold, so install it first
  - cuda-toolkit=11.7.0
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - pandas=1.5.1
  - scikit-learn=1.1.0
  - networkx=2.8.4
  - requests
  - rdkit=2022.03.3
  - e3nn=0.5.1
  - pybind11=2.11.1
  - pyg=2.2.0
  - pytorch-spline-conv=1.2.1
  - torchmetrics=0.11.0
  - gradio=3.50
  - pip:
    - pytorch-lightning==1.9.5
    - fair-esm[esmfold]==2.0.0
    - git+https://github.com/NVIDIA/dllogger.git
    - git+https://github.com/aqlaboratory/openfold.git@cf177c0c4a19bec0c380ff9758a18061c3248f85
