# This file was created from the following template:
# https://github.com/github/super-linter/blob/master/TEMPLATES/linter.yml
---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: DiffDock Linter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [master]
  pull_request:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: DiffDock Linter
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Code Linter
        # Use slim image because it's faster to set up.
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Point the Github action to our config files.
          LINTER_RULES_PATH: /
          LOG_LEVEL: NOTICE
          # Which languages / linters to run.
          VALIDATE_PYTHON_FLAKE8: true
          # NOTE(ken): disabling black CI step temporarily, because it seems to be suggesting changes
          #   in files not included in the whitelist in pyproject.toml, blocking PRs
          # VALIDATE_PYTHON_BLACK: true
          # PYTHON_BLACK_CONFIG_FILE: pyproject.toml 

# https://github.community/t/concurrecy-not-work-for-push/183068/7
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true